version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
sphinx:
  configuration: docs/conf.py
  builder: html
formats:
  - pdf
  - epub
  - htmlzip

python:
  install:
    - requirements: docs/requirements.txt
